hash-format = "sha256"

[[files]]
file = "MODS.md"
hash = "93122b3824096746b6fc1aac4756d9a9e32769db34f9f9b91eb6811742cc5025"

[[files]]
file = "config/Better-Stack-Count-config.json"
hash = "a83f277ab2f367e706da512e3986f4ce4fe62033949c71225bfab0363bfdb89b"

[[files]]
file = "config/CleanView.json"
hash = "4f7242f9f8d63170840e98fd3bbd6e95afe974ab21b4f6f35445ce9ed7af1f8c"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "edfe78d985fe67dce28104f3d87673e94c89134144451c291ecedcd2e2c3b480"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "0eaad2630bd70ade719f7810e805810ada25379269ea194e43d3eea30c51dec0"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "914ff467c04be14074e19741255b5f890db2bc0458554b984b2c02d3674bb824"

[[files]]
file = "config/NoChatReports/NCR-ServerPreferences.json"
hash = "df32843b853e0a493ef3a9b1e39276818294353fbb0d833f7f61e77da0f5bca1"

[[files]]
file = "config/NoChatReports/README.md"
hash = "c52b76ccad2bd1063a22c7f6bb9e7c5db6b00fb53a6fd605585972ee0e5fc01f"

[[files]]
file = "config/anchoroptimizer.json"
hash = "3febe0c3b30a6cc9a0c174a9277388629d262cd16a803f5d3d67fdc3745cd76a"

[[files]]
file = "config/appleskin.json5"
hash = "ae87f2d1b38dfd4b1e0767dfeb539261deaaf4fd2eb73692afcbaac7147855b9"

[[files]]
file = "config/better_crosshair.json"
hash = "abfaf694fb4c4fa4027aa64e2a5201c996e2c7fec7e9d002b9ecc7c80d6d1f29"

[[files]]
file = "config/betterhurtcam.toml"
hash = "4580744030f0e75cea55b75f6e10c33b6a02e5fef750d6592147991d9d577b0c"

[[files]]
file = "config/bettershields.toml"
hash = "1fc4719f03cf9e6202935222617bf4d6bbdf8e5157241d0c0bad3bb99a0c92ab"

[[files]]
file = "config/bobby.conf"
hash = "268dec92df483058dbfbb779766afcec91741c2851f3dd5e22a42e713a6c064e"

[[files]]
file = "config/carpet/default_carpet.conf"
hash = "76f87589fb0d40c495ef1d61a926cd75b70dc26304d65d89fa08840bee43671c"

[[files]]
file = "config/cloud_configs.json"
hash = "87ec91e0ed4edf3468c1928fc4a71b4019a8ed13951217aadff3677d64601e74"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/consumableoptimizer.json"
hash = "3febe0c3b30a6cc9a0c174a9277388629d262cd16a803f5d3d67fdc3745cd76a"

[[files]]
file = "config/controlify.json"
hash = "b7883ec700185e0b706570de4301dfbbce28b8a55097988b2aa25dffce89b317"

[[files]]
file = "config/controllermod-common.toml"
hash = "5b275b48571faa6261fab91f1dac7af29cabc508701df7bd62fb053b63db93ce"

[[files]]
file = "config/crosshairaddons.json"
hash = "21b8b27216d3e87f3459d4a1945670df0ea874a5ebda48c56a8e628fd953ee45"

[[files]]
file = "config/custom-hud/config.json"
hash = "99fd47d9a67c9c0284453823aef8c8fc1ccc91b5894a1e40cae4ff043eec33b4"

[[files]]
file = "config/custom-hud/profiles/Example Profile.txt"
hash = "1fff0040fd7d3454825d206d7a4acfbc7bddb45494a18a2274090c3fd0e6a32a"

[[files]]
file = "config/custom-hud/profiles/F3 Clone.txt"
hash = "fe7f40b0125df8acb5d2da031bb2e7836579b87fe8dda192e8ddbdc4b05ed90a"

[[files]]
file = "config/custom-hud/profiles/New Profile 1.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/custom-hud/profiles/Simple.txt"
hash = "f341bb5fe4a5af73316e38118ed7f4fb38b562efe80fd378d7145fecfff834a3"

[[files]]
file = "config/customtooltips_config.json5"
hash = "187e8abc0135ed0f8f7f9a2add2641fb25fa0c1dcc5b62f0fac231984fc66cc8"

[[files]]
file = "config/dho.json"
hash = "007df1c8f55d2823664ad2f0457bb969febfc56432464932ae42bedb33fe25ab"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/dynamichud.json5"
hash = "b5174493923a32601581de87a22c8f59df27c698e6e238a9b1490613064ebff0"

[[files]]
file = "config/elytra-pitch-helper.json"
hash = "d9d8282407cd45917370ee1c29a1b981c4110594cf96bb9ec7e116d69e8fc28d"

[[files]]
file = "config/entityculling.json"
hash = "07ccfa8d4edc6928ec566ce42a16d234436ee678b5ddc258431abf265f4f46f7"

[[files]]
file = "config/exordium.json"
hash = "eaad4ac3db66cca87315a1ad0de39344d55950f20f80181773160786935cdde6"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "2f138a43277188377036d83a9d875dcef02d06f714e20f9405ef07d3fbf56779"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/forgeconfigapiport.toml"
hash = "40dbe5b348f89b8ded62bcdfe32807ffc3e78fa8e0f81607a739580019fe5450"

[[files]]
file = "config/fullbrightnesstoggle/laststate.txt"
hash = "c80a18368256aebb883daceb749cea549846c0e087554221786f238c5f88a68f"

[[files]]
file = "config/guiscalesplitter.json"
hash = "2c853b3d807a427031b727089caaf53d9d786c0f0209b98d607a9668c7ebf2cf"

[[files]]
file = "config/ias.json"
hash = "b3bec15ebed5329d3534ff7219867ef4d3fc3a735983a10679de25d2c632711f"

[[files]]
file = "config/inventoryhud.json"
hash = "55a1a4d58c9ed9bb7fc44c42a89f91fe32d2cdb7a28534849e980da2e5c665fe"

[[files]]
file = "config/inventoryscale.json"
hash = "0de3606ba08b446e3c3bf8e8b5f6840d9d6da737110aef2a8f1f9e6acb677c10"

[[files]]
file = "config/item-name-changer/item_data.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/lithium.properties"
hash = "76765e8e5ff8e927d80beb0739aababcf36e7babfd94262f2afece256cc5cd2e"

[[files]]
file = "config/modelfix-client.json"
hash = "7e02c1d587a4c011b0b18080b7ba7451bd44535159a52c4c0c9a94b863334678"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/nuit-config.json"
hash = "4596aa7d6c320ed978329a9c3967acd74aff08b75f9151d98e762ee853d1e98f"

[[files]]
file = "config/nuit-interop.json"
hash = "839c3f69be9c956bb7af12e80017bbf1b3ec389d9d520d076c5627a6f7180c39"

[[files]]
file = "config/shieldfixes.json"
hash = "6f11c363da0dac6c9a14c9a4067fdd73118a7b098a850eb814825e49446fd1c1"

[[files]]
file = "config/sodium-extra-options.json"
hash = "3a7c54d4b97f7897ba1cd247337bb48d8e6397dcebc028880f342c24b16c0cd3"

[[files]]
file = "config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "cb51390959dbc2d912a7c0c3d165724adab0ec571f59860b2beb7b39bc9fda21"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "be46b7dafa3a3904c4b465be27fdc94c634882ba2ef15f17085b5cb65f9424c7"

[[files]]
file = "config/sodiumextras-client.toml"
hash = "135bc55c484c11c07e2abfdb2bb9e9eb7f799b6a959cad277c333db83160982a"

[[files]]
file = "config/totemcounter.toml"
hash = "ac47a7ee7371a7dfb94eb8ea2c593cba9b42c0091a981dcb484b34eab60df724"

[[files]]
file = "config/totemtweaks.json"
hash = "9e5d104b10959a2bde0829a03ebf76a914998ab5a264df744923755992ac5107"

[[files]]
file = "config/ukulib.toml"
hash = "381b3be9c8daf611db35e018b71080be5d459385523d08e8e43568bb51dd11ce"

[[files]]
file = "config/ukus-armor-hud.toml"
hash = "e4a259bd24d18f6904f469b1303f5ff130a19d0368600804062e874fcd860443"

[[files]]
file = "config/unionlib-client.toml"
hash = "3e0a80b5488058b510b9ffb7d1ef84e7140a321fbdb34b8b13817b4f8636f250"

[[files]]
file = "config/unionlib-common.toml"
hash = "5fcd5793de154b99c3eac8da908e3be12b5552058b3e5142c6bf699c75bf2c54"

[[files]]
file = "config/unionlib-server.toml"
hash = "b866ef93b7aaf4f256e4f406bd2e0ca6c58c4ddc967b64767ae7d50d066500fb"

[[files]]
file = "config/walksyambienceV2.json"
hash = "19db9ddfb816302c1c559e30c48c5053087192166f85312b38082fcf9a891d63"

[[files]]
file = "config/walksycustomhitboxes.json"
hash = "d92a7984e4ab99cb681582124f3df1493b52ec06cb1e9cf835e966ab3456fd0d"

[[files]]
file = "config/walksyshieldstatus.json"
hash = "35323455740a802c981f640a277731e4954304504a873fcc1bdca390d1f4ea9c"

[[files]]
file = "config/walksytotempopchams.json"
hash = "c54bfd1ff06ea9b0bc32bd7b953d6a9b9404c4114c07d2684c37addb41504cfa"

[[files]]
file = "config/widgets.nbt"
hash = "c4b20aae5891e637e2e0c24944182311f5ab70ffb403757062c554c62d821262"

[[files]]
file = "config/widgets.nbt.backup"
hash = "c4b20aae5891e637e2e0c24944182311f5ab70ffb403757062c554c62d821262"

[[files]]
file = "config/xaerominimap.txt"
hash = "066cbfbde05ca9458c1eaea1a4625195a456fcde7052e75fe9d8cc99633777c1"

[[files]]
file = "config/yacl.json5"
hash = "139784dec1158a8da468b64b9d9b44a61d3c8eadaa5d7a8530f02be6a9625660"

[[files]]
file = "config/zoomify.json"
hash = "60a78fe1b271ce9b53e295235eb5a7cdb3a8692ca583fdaa7f5bc09f9049e2f4"

[[files]]
file = "mods/ambience-v2.pw.toml"
hash = "21930edf65076b3f37544b1f4f45cfd0652b2fb6bb8cb6d6a12065f56f58eb63"
metafile = true

[[files]]
file = "mods/anchoroptimizer.pw.toml"
hash = "c51217b39da44ab303d75c0047179c635d0529fba85405f8ec6ffb69f12991fc"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "417e4f42790407e6fb4dfcb03cd4abcdf3aa00f4dcef3f3a2edec1a3e1a9a3ef"
metafile = true

[[files]]
file = "mods/auto-sprint-fix.pw.toml"
hash = "94e8658b9eabf2fe2b596d45ec34d3157c047b89a2afa5767c60063b0fcd13c6"
metafile = true

[[files]]
file = "mods/better-stack-count.pw.toml"
hash = "edaf27d71c2f2d54fa9f8d3aa40ab8efa0843522a54c63067104d32a8e749c9f"
metafile = true

[[files]]
file = "mods/betterhurtcam.pw.toml"
hash = "9436085bae308ace17b565639c51bd7e865c282cd2440b85fd74484b4ccaa57d"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "783f6391e53272943cce060fd820d1c5b7cbdf94df1341f250bf09eaa296171c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1d6a658473589e15d906a591257e1ed769b6fcb298c4affe32163a9ca2316b33"
metafile = true

[[files]]
file = "mods/carpet-pvp.pw.toml"
hash = "552abc4ac05d929df3f6ef93a10171fe56946bd41d5e6d74e9b53eba3d204018"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "b30c875fbf625946b7e48653b176b37ecd45c8255747cbfbfa97513c4e997830"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/cloud_tweaks.pw.toml"
hash = "41884f48cf2a7830153ee6f22819c55275ba54f9c28664576c6a517ac7e69663"
metafile = true

[[files]]
file = "mods/complete-shield-fixes.pw.toml"
hash = "2c2910aa9681c3a270f9d0da23a2c8cbe0fc156fba90e221cef8b80b1dd81006"
metafile = true

[[files]]
file = "mods/consumableoptimizer.pw.toml"
hash = "56df8e9434c5106ae4795e2a7d0c8dc57f21c1a49642bd84efb192ff87cee39c"
metafile = true

[[files]]
file = "mods/cps-plus.pw.toml"
hash = "cb195e2c5dd1e0151f2531729a510563541ce54a161d2f38d4512c8163232d89"
metafile = true

[[files]]
file = "mods/crosshair-addons-public.pw.toml"
hash = "34e01eecb24d9c864a28b1c0a9a4ba26cc6d697cc0ac118261ff2e9f24a71980"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f32c30de1ae7dbeeae00b654eb15ea358c6d26f631dc292bdb88dba9c30a8cc8"
metafile = true

[[files]]
file = "mods/custom-crosshair-mod.pw.toml"
hash = "eb6d555198482fe65deffef231a950285711cda14304585bf95901304c6dcbeb"
metafile = true

[[files]]
file = "mods/custom-tooltips.pw.toml"
hash = "8c1d3b0b73d2a463b8acaa1e46f7458dc3e56240d09e5fd673734b15b9d6f66d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "04851cf23a0fef9e213180bf5926b705c5ad2d0b04d41934b915cc1ccfabd841"
metafile = true

[[files]]
file = "mods/dynamichud.pw.toml"
hash = "71c051d223d2f7f49ca10428036c583e4b759352f0b74f9bb539b427fafea832"
metafile = true

[[files]]
file = "mods/elytrapitch.pw.toml"
hash = "28144780cc0f5e395b875615aa2737cbc4cda657ba066a62039b0b4729262d75"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d03670996f0592cec08a20dcb81227ae6145e8ac483a9b4432dc62569a253e30"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "00e81838a75f44a161ce5670cfb0899c9d0e44f4da736e9f81b4264468041643"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "49d3797fa3451ac53b805fcf655d7fc59ba2eaeb967b3cc2b7f77ce40502669e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b2f2ef63febe17f277635827ca474e1aeae321e8a82bef78942116f95d00250a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1ef554f7a8d5f7ed4bc21316e034eeef3430dc306012c0a706bd4c3e4ac253aa"
metafile = true

[[files]]
file = "mods/gui-scale-splitter.pw.toml"
hash = "b9f7f8c634a2c412e4656a5a773f04dfa086fe81e8705757e7515ea822c2a4e5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "22f0504f66807f6fae2103924e98d990a0d547271f886b6fabaedafdb8045333"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "778c0f570039d693859c65efe72d58d228f9c387c9727acd4447a3feb1ce2d10"
metafile = true

[[files]]
file = "mods/inventoryscale.pw.toml"
hash = "1eb4c5d9e2ac6daab429e7738b2171619ecf84fb7c69454a7cf95ca5f41b95aa"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e03fc0b0c151c5c072ac399d27b5c4268a093c41be73f3b1578d050bb49211f3"
metafile = true

[[files]]
file = "mods/item-name-changer.pw.toml"
hash = "b326c837817a7079759a0f897b907458dc9583e254222dd9492c13c806926c77"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/marlow-crystal-optimizer.pw.toml"
hash = "6e74d2b36d6867cb5cafa0d6a1d2a6f0699de0d08507060a6b838cf09e03fd7f"
metafile = true

[[files]]
file = "mods/mcinspects.pw.toml"
hash = "fe04514cccb20e21e5b167b710a3bdf31748a1e5c00e9d95cc805ca4637f72f4"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "78946e7851174a7462125185cb6306f5bac4fe5b90a3f4396cd8a79d56084661"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "88c6edc1712f4f0cd915cd723b9e0296924d454b3855a719d2962103b2b92bea"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "108aae1d2a8f03fffeb5f36e874d378d521f9779cf476e4e60b7f2a8043252f6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "95ff1073b74b23e62cae94569ffb63e6e2f244d99a6d1a38c4a26bdd183a64eb"
metafile = true

[[files]]
file = "mods/nowheel.pw.toml"
hash = "59aec783258e6914bd33fbcd51606242c07c1ed56db2a83bd2e58a1d8e1ed24d"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "00942cd2fd2775f47e1451a1705fcc0bc282bc0e7f19eafbaea70866478244b4"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "8c3777fcf9615b961fa6c1f44ae002cba0d0d16cf62041ef2fa23e4e481bc56e"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "6b2abdc14fca0b9b42b5678e7c65af8b93d5032f0e4b0d2fbd93295903489d50"
metafile = true

[[files]]
file = "mods/rebind-quick-swap.pw.toml"
hash = "2177a84395bb15488a27e751944b8e34cbda7faac36b9c51d19e9455cf2bae5d"
metafile = true

[[files]]
file = "mods/recursiveresources.pw.toml"
hash = "ad408a54bf2061ccb999daa3e28357c1e4ca4d6e28ee34e425a69fa0e0098500"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "e70e8529c163ced6575c52810ed56b7dbe2fdf7348111680c82e1f411c52f3ed"
metafile = true

[[files]]
file = "mods/settingsmanagerlib.pw.toml"
hash = "1629dbceecccd429066f0e8e7260fc3ff89b18aa6f3122a75a7483cc057b0d88"
metafile = true

[[files]]
file = "mods/shield-statuses.pw.toml"
hash = "562d104e8e695b9f6450748c18ed51e68c7103114894cba6945bb5cea76b5c57"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "15fb8e896fed5e78ff654563c3f20a64069a43f9d073ab0ee277b31d1e4ea776"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "56a0e243140dc1dbdb89c5a7a1cbcbe6e8d6da5499242bd1eabf548bbb8e3481"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "30fc7545fc027bc3d3dd3e082c17281dfe7399aaaff6d1700ef7467ef873e3db"
metafile = true

[[files]]
file = "mods/sodium-fullbright.pw.toml"
hash = "a0e206f86721e424f917ae72071b52a37f7b6c65d4772c21e83a1f1b83616f6a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "09d2dbee70e91e8859e6f62e4181a80264d6dd24cc686fbedb93dda9f69fdfe6"
metafile = true

[[files]]
file = "mods/totemcounter.pw.toml"
hash = "afd97c9755d71df904e82f0e349cde968dc84f6f1e56b09aad8e8d85ad2dd264"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "a29f4316b31b7eb853eaf7f1ac3989b8a9d1907834afd779a3a88e012dbc96ee"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "644da4f0a1e42afb5708bd236f79005976d244d80150bef9c7f5bdff79362b1e"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "d5a6f65c0a04360a54bf687bcdc429d5ff9399c15e832e9f6a43efcbfba2ec01"
metafile = true

[[files]]
file = "mods/walksylib.pw.toml"
hash = "8d1dc0c2323e9a8cd5e52d619336c0202e6e7ac36bffe5c96ed5e316a5c9f63a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e2993e3a790166cb2f6efdc2f8ebb970bf1a3481722ca3c00d53d0764931b3e9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "options.txt"
hash = "234ad193a817b797907536cf09294a9bf5d60f3819f46f6f0b6d9b634494a113"

[[files]]
file = "resourcepacks/cleanview.pw.toml"
hash = "0ea44c20b861577c389da6e0c94eee99976aa45e51277b34895437ca56e6baf9"
metafile = true

[[files]]
file = "resourcepacks/no-cave-ambience.pw.toml"
hash = "5d3d4799be9359ad7299b17d30777d02ee23cb0603e1ba9bc5b3961a9ef76133"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/kappa-shader.pw.toml"
hash = "a01d824c592eebca3df5b5af6aed07839eb8b544de20a2e4f276cb0622b203c9"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
