hash-format = "sha256"

[[files]]
file = "MODS.md"
hash = "6abe8f0cf313023b1f60eb2ffe73eca12af1962f7dcb8c7892f80cfb1e6e961c"

[[files]]
file = "OPTIONS.md"
hash = "6529ed191392f890f8c56a8f34707ee5b1490bc5d7e7134c5cd517c84f2f2de2"

[[files]]
file = "config-archived/Better-Stack-Count-config.json"
hash = "d216e56a36e6bfdb3a75d66bf6a397d4643c870469b68ba3e72d46b348268d85"

[[files]]
file = "config-archived/CleanView.json"
hash = "f87ad52dbe666eaf7508e35c54309e4d0c163101ecaad376dda15ebe21991682"

[[files]]
file = "config-archived/NoChatReports/NCR-Client.json"
hash = "959e8c6596226e892424baa4845afef843172d818688109b68b3d6420daeb19b"

[[files]]
file = "config-archived/NoChatReports/NCR-Common.json"
hash = "8309da0706c1a704d1ddd8865b1f4143f472563c286c184ebe7b44d607138279"

[[files]]
file = "config-archived/NoChatReports/NCR-Encryption.json"
hash = "d276b062d4eb599fc8110b71c6f31f875a54eae2541f275c17b281dc7edf0755"

[[files]]
file = "config-archived/NoChatReports/NCR-ServerPreferences.json"
hash = "f6950e59bd073d3740e49a88167ccf20cee29cb6a61ab673a4fb28cd7fccd509"

[[files]]
file = "config-archived/NoChatReports/README.md"
hash = "c52b76ccad2bd1063a22c7f6bb9e7c5db6b00fb53a6fd605585972ee0e5fc01f"

[[files]]
file = "config-archived/anchoroptimizer.json"
hash = "9536f7b6b7be4c6d3abdfce03d1ed4ac8071897ac033e9812352a0ab5d4776e3"

[[files]]
file = "config-archived/appleskin.json5"
hash = "161f9103e28ed86fbfab7859da833bccd00f9c6d5404dc1f9716b869b2887abc"

[[files]]
file = "config-archived/better_crosshair.json"
hash = "ac5e12f61b4d160b2c5e86f300e289169873ad7fbbbb4adafcdc80b2b3d00e17"

[[files]]
file = "config-archived/betterhurtcam.toml"
hash = "4580744030f0e75cea55b75f6e10c33b6a02e5fef750d6592147991d9d577b0c"

[[files]]
file = "config-archived/bettershields.toml"
hash = "1fc4719f03cf9e6202935222617bf4d6bbdf8e5157241d0c0bad3bb99a0c92ab"

[[files]]
file = "config-archived/bobby.conf"
hash = "268dec92df483058dbfbb779766afcec91741c2851f3dd5e22a42e713a6c064e"

[[files]]
file = "config-archived/carpet/default_carpet.conf"
hash = "76f87589fb0d40c495ef1d61a926cd75b70dc26304d65d89fa08840bee43671c"

[[files]]
file = "config-archived/collective.json5"
hash = "191970b04075f4fe27258dd9e1cf1a971420eea473fde5b1843d21881742d4e9"

[[files]]
file = "config-archived/consumableoptimizer.json"
hash = "9536f7b6b7be4c6d3abdfce03d1ed4ac8071897ac033e9812352a0ab5d4776e3"

[[files]]
file = "config-archived/controlify.json"
hash = "6d75608272157edc5ddb69ac667f58ca473d69af58615954f6b312a7407e62d4"

[[files]]
file = "config-archived/controllermod-common.toml"
hash = "9b5d457f2a5661f8a08ef9ae86b72cde28e6edaf2f4e6d89d8770bbc4896e89a"

[[files]]
file = "config-archived/crosshairaddons.json"
hash = "d1d570963c3f7dd107286ce123b720c3c89f95bb6e27ffc508ccee1f45d7a55f"

[[files]]
file = "config-archived/custom-hud/config.json"
hash = "12ad6fbbee825fd02e813e465335b2a410af743d746de8d5a6a9a52098e963bf"

[[files]]
file = "config-archived/custom-hud/profiles/Example Profile.txt"
hash = "0cadaa245fb3ff1ac8a74b1674979af2f9c5ee30aad969e1a7ec49015360926a"

[[files]]
file = "config-archived/custom-hud/profiles/F3 Clone.txt"
hash = "cde21323a888b6b6e5e67b397edec17636e8f50fd04a43320d04bce9b9b8ecfa"

[[files]]
file = "config-archived/custom-hud/profiles/New Profile 1.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config-archived/custom-hud/profiles/Simple.txt"
hash = "f341bb5fe4a5af73316e38118ed7f4fb38b562efe80fd378d7145fecfff834a3"

[[files]]
file = "config-archived/customtooltips_config.json5"
hash = "95d7b432a36d0fe839358dbcafd82bb8108cbff31b4002ae2e8304a2567c9872"

[[files]]
file = "config-archived/dho.json"
hash = "a0e21432b263c45ccf92b5f341bfcf67dcf4bc4d5ba6fe9e50056b574b4a61c2"

[[files]]
file = "config-archived/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config-archived/dynamichud.json5"
hash = "01f302edf38524df2a3efebc891bd642ed933cdee869c998edeebadd436403e8"

[[files]]
file = "config-archived/elytra-pitch-helper.json"
hash = "e2e3629983f5dbd2cb51638697d8fd4656a0548e84ae75578131fb6c18b567ff"

[[files]]
file = "config-archived/entityculling.json"
hash = "8de69f9ca665da220cd9d542e0321287ade1701154f9d322063ebd47756ef783"

[[files]]
file = "config-archived/exordium.json"
hash = "9a56830d4d371b7a3c6be4318bda5814ecdd8b3c3d89ea7804b9838c84ecc813"

[[files]]
file = "config-archived/fabric/indigo-renderer.properties"
hash = "2f138a43277188377036d83a9d875dcef02d06f714e20f9405ef07d3fbf56779"

[[files]]
file = "config-archived/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config-archived/forgeconfigapiport.toml"
hash = "40dbe5b348f89b8ded62bcdfe32807ffc3e78fa8e0f81607a739580019fe5450"

[[files]]
file = "config-archived/fullbrightnesstoggle/laststate.txt"
hash = "fa43a4356cc0f41f64f01012753cda9e713dd4d0751ad53bdee39e27fdac1ccd"

[[files]]
file = "config-archived/guiscalesplitter.json"
hash = "beb6f1a50fad28a121d23e60b27a1675236b0c6609218f76e8d955bcdef03218"

[[files]]
file = "config-archived/ias.json"
hash = "92e3e4bbf87447b2f0bbb5a5eb765d72b0ff6b56b7a71c2d6f011941f2b39db8"

[[files]]
file = "config-archived/inventoryscale.json"
hash = "bb124fd092539607f5fb7929d6826d4221acad1702039b5c61195caac264c45d"

[[files]]
file = "config-archived/item-name-changer/item_data.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config-archived/lithium.properties"
hash = "76765e8e5ff8e927d80beb0739aababcf36e7babfd94262f2afece256cc5cd2e"

[[files]]
file = "config-archived/modelfix-client.json"
hash = "6f83b7ac4309509c3c51d112ee40494aa38359bac63cebb2732a9df61610b022"

[[files]]
file = "config-archived/modmenu.json"
hash = "72d9d0986e0ee20e13e9989e7f0cd8e5aae3ad37a9505de231aba31e15ac16b3"

[[files]]
file = "config-archived/nuit-config.json"
hash = "b7f5e76bdfd058500fb70be10c64937083e757f3a8325eaaa815610ebabfd870"

[[files]]
file = "config-archived/nuit-interop.json"
hash = "7fad585ae3813048a472316cf06c4fd2a10dce7fa9f21009a067405f1fa853f3"

[[files]]
file = "config-archived/shieldfixes.json"
hash = "6bda227b8bf9ef82f284ec1b6e0e7e734982ecb61060a7abfb18586c96e8ca60"

[[files]]
file = "config-archived/sodium-extra-options.json"
hash = "e376579723352a4565aee734fa7d8d9d44f6c9bb3852ba3b258dbae684228902"

[[files]]
file = "config-archived/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config-archived/sodium-fingerprint.json"
hash = "5b52388ae233475946db33266446be7300ecce01f89218089ef9ae945dda4f3c"

[[files]]
file = "config-archived/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config-archived/sodium-options.json"
hash = "0853f28d7fce5b58307b48a9f149efaec9d7816c761cbb845a6a45eb267ac79d"

[[files]]
file = "config-archived/sodiumextras-client.toml"
hash = "135bc55c484c11c07e2abfdb2bb9e9eb7f799b6a959cad277c333db83160982a"

[[files]]
file = "config-archived/totemcounter.toml"
hash = "ac47a7ee7371a7dfb94eb8ea2c593cba9b42c0091a981dcb484b34eab60df724"

[[files]]
file = "config-archived/totemtweaks.json"
hash = "21e4fed7ab108c55b616bc87dbb99aca592d2f4307c86f99283492d3ed316849"

[[files]]
file = "config-archived/ukulib.toml"
hash = "381b3be9c8daf611db35e018b71080be5d459385523d08e8e43568bb51dd11ce"

[[files]]
file = "config-archived/ukus-armor-hud.toml"
hash = "e4a259bd24d18f6904f469b1303f5ff130a19d0368600804062e874fcd860443"

[[files]]
file = "config-archived/unionlib-client.toml"
hash = "90defb93bef373cc4092f8e4c00d97c658f8f3deb1fce5996bd5db7c7dee70b3"

[[files]]
file = "config-archived/unionlib-common.toml"
hash = "eb32da02cf9b1528f6682d160aa33f983e2847badb204ee7dd5900dc69b29148"

[[files]]
file = "config-archived/unionlib-server.toml"
hash = "fc800170c148a3e533d9efc8633d92b98f12c3e48ad44db5500f31598131535b"

[[files]]
file = "config-archived/walksyambienceV2.json"
hash = "82e44ceca2d2831a45c75c63ca81754819c3f71b2e1a8568f62cd35b4b67df44"

[[files]]
file = "config-archived/walksycustomhitboxes.json"
hash = "80bd07a0b2476746e146c5794d864f8d4bb5b44e8f4698740bd9bde61ce4c50a"

[[files]]
file = "config-archived/walksyshieldstatus.json"
hash = "d64f899da4d8cabe0850edde3caf6bcdcfebc8f7a8b3752cde2673d06fce0170"

[[files]]
file = "config-archived/walksytotempopchams.json"
hash = "a0d385866dfcb4e408dbe2ee4f2162af22c87b00a620ed6e343e3fc6658548bb"

[[files]]
file = "config-archived/widgets.nbt"
hash = "c4b20aae5891e637e2e0c24944182311f5ab70ffb403757062c554c62d821262"

[[files]]
file = "config-archived/widgets.nbt.backup"
hash = "c4b20aae5891e637e2e0c24944182311f5ab70ffb403757062c554c62d821262"

[[files]]
file = "config-archived/xaerominimap.txt"
hash = "066cbfbde05ca9458c1eaea1a4625195a456fcde7052e75fe9d8cc99633777c1"

[[files]]
file = "config-archived/yacl.json5"
hash = "e59973486e143c57eeffb7962076106059f3baef39bd2d62a1e4b052b4cf9de6"

[[files]]
file = "config-archived/zoomify.json"
hash = "b8aeffc7a72bdc136046cf7434e26e9cc46d3d8ebc2fcf07a3ad8fd3b06fe280"

[[files]]
file = "config/inventoryhud.json"
hash = "3ce1a3bfdd4d2d25815c786c9d7838f3cf064743f6bf872cba21e29e4087316e"

[[files]]
file = "mods/anchoroptimizer.pw.toml"
hash = "fc08a7a1cecb9019e87b6ef255a3c34b7a2a81802b1bfdea3f2d2c8b79213ab8"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ca3ae2608987185814c118388f28057f729d866ee1abbc97f3650141d213fa35"
metafile = true

[[files]]
file = "mods/attribute-swap-timer-ported.pw.toml"
hash = "93cf273e116d97502d20753c76b6c86358c5609c8ebf07c9171b660150758cd5"
metafile = true

[[files]]
file = "mods/auto-sprint-fix.pw.toml"
hash = "86b6e327e379040008fa7575334e6713b61b80df5d43c65f2249e52ba74eaa6a"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "222051963124274280e95417029d355d16cd6806af884217f834a6d599af6dc9"
metafile = true

[[files]]
file = "mods/betterhurtcam.pw.toml"
hash = "6bb57ee0ac9df8a976c0b3af8264f2c10da36c03b90aad7954d29363183191f2"
metafile = true

[[files]]
file = "mods/bindcommands.pw.toml"
hash = "1019b0b703e1d642026659fdeed956892996716c1d18c453dc6b8d728da8eb5a"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e097f95b8818e0999b4e867351745441f90c9bcf2a9c68cd19d5d708da4a4a1"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/carpet-pvp.pw.toml"
hash = "552abc4ac05d929df3f6ef93a10171fe56946bd41d5e6d74e9b53eba3d204018"
metafile = true

[[files]]
file = "mods/clean-view-particles.pw.toml"
hash = "39db4793651a16a93f29f290ee7f6c5e3bcabb875bde40f36d76abeb5eb7a0ff"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "a5f67311e64ea67e8097c1fdd4d20cf11e1c5236334b5becabad7dabdae975db"
metafile = true

[[files]]
file = "mods/complete-shield-fixes.pw.toml"
hash = "87091992e7b932b8135174344d52748bcb8ebae80202c101380e45cf5c442058"
metafile = true

[[files]]
file = "mods/consumableoptimizer.pw.toml"
hash = "3a099dd9a533e1939a27537d09c2e6f32571a8c17fa593ee9847a7b084eca74a"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d8e2eb843f684b6abe48010c4ebf3e1300bd0fe9a4132e2744757d850171f4b7"
metafile = true

[[files]]
file = "mods/crosshair-addons-public.pw.toml"
hash = "ce907c287c097274dc53e799471d0d747e542d75a329d0e488f8148921678142"
metafile = true

[[files]]
file = "mods/crosshair-indicator.pw.toml"
hash = "f66bfe5c62c2d0f293fbecd37f1f977c111d73f18efd79202ed7b01114417a3d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "982801b4473e11e6f8c5899f18a260515239dfce397c650c6920fc6ae03f6abb"
metafile = true

[[files]]
file = "mods/custom-tooltips.pw.toml"
hash = "8c1d3b0b73d2a463b8acaa1e46f7458dc3e56240d09e5fd673734b15b9d6f66d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7b83af5380faba6641a6fdf27e239eba79846f6b66a65da810860a8cb1e86ee4"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "c507cb3ad0ba5406f6bcca784ad22fa13bf95616fa9ace186f0b6c3b2cfdc8ba"
metafile = true

[[files]]
file = "mods/elytrapitch.pw.toml"
hash = "221c0d456abcbf9a9bf674dbb40141d1a638dff6ec6050e9325c01e8f4e0b69e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "84e1bce3358e57bcb8c0156872f769550137fd2cf5c0745e58dc9ea65206225b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "ec167c40c324688e0fa677527062f06e8c6c7c10f79f5e6ec7a61b478d44e9b6"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "38c950bdd47f54d586d1e9ae0c714574885423941ed7799f11b776d2b05ed02f"
metafile = true

[[files]]
file = "mods/item-name-changer.pw.toml"
hash = "b326c837817a7079759a0f897b907458dc9583e254222dd9492c13c806926c77"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "590d8c454461493a6a60a6efe9a43bcb94231e7b55c7382f1aa209ad7a572f99"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "ad1110e02639ce1dd8afd73ca567d44fbe592c662d656fee567b6c1f7ced308d"
metafile = true

[[files]]
file = "mods/marlow-crystal-optimizer.pw.toml"
hash = "f751fe3e11a8989b880bd12ebe14688944289c5359e026ff414cd00f0051a576"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e4b9192ce7f54715dde7eb682ebab23aaaac10658b1bd08ba553a5f99b0124d1"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/nowheel.pw.toml"
hash = "59aec783258e6914bd33fbcd51606242c07c1ed56db2a83bd2e58a1d8e1ed24d"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "ab6def9d98d3f5bf12f78845bdb770a19d5ca590c571e60184e537ffa14dcbee"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "565c943b5006c36137a2fe55e4b8433e134c3d1011a37c5f5124cee67b671cb8"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "a98b989a1096809021d33c24371582eed29586684f1134ec915bec2b7c2fae5b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "77f6ba8f063840c0d8a58bba2cedc2743d136c1d51cdd28d3506d19e167e08d5"
metafile = true

[[files]]
file = "mods/settingsmanagerlib.pw.toml"
hash = "b4bf0585de0192e0e3bc8e865e4af839723f1de674fca1c07963799e66079712"
metafile = true

[[files]]
file = "mods/shield-statuses.pw.toml"
hash = "2d19216d70c39ec91cb12767b669ddbb59b33c8fe7c5390151b768112e7344bf"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "fb952e6a0454ecbcdc40ed90b9cf7a7c8a9f86234f6b753743dfbba32b7e8535"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "c064e431015fe06786c17e18b8cfc28751a994e2ee251a357c0043a72f649403"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium-fullbright.pw.toml"
hash = "1254d15441bcb419d617a6b83b4d8496cd2b15a1a4960d229141584dd4cd87c3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0b4c98b7b25cdfcbb7882c32155d597f0fcaa37aa301b14baf4ad8cab65fea85"
metafile = true

[[files]]
file = "mods/totemcounter.pw.toml"
hash = "90ae17111873bc0a28eb55702fe1d2654e4f02029b214c6ae728917a7b01e8df"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "7223f44c82bc2abc66ec3fad842de14cf58a7afa775ad2f361948ccd10853c47"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "dbce22b3882cfd6ed55a992601bea74aeefdd4228347e7c4d34ba5625e44674f"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "095c72f3e53174c217c4b6a8746e3e9ef51289ecb38ecb6e29db79800ff0c911"
metafile = true

[[files]]
file = "mods/walksylib.pw.toml"
hash = "a9430f9074c470dd140d35ef21ee6a92f63511345ba5f7e0e9d8fa77ab0f327d"
metafile = true

[[files]]
file = "mods/wwaypoints.pw.toml"
hash = "9c9389566b2a364b41b46ca4d73fe46752c0f7c8f0d5622041ef7bf78c393b15"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3ff0c2f005f2523f157b776f0e870494a8e8ec0ff77cb7e965c88b4e2090efdb"
metafile = true

[[files]]
file = "options.txt"
hash = "e0c00b4eb7c9cc81f947e3fff9c2e80903425893fbb83fb4817350cc2855ee29"

[[files]]
file = "resourcepacks/better-low-shield.pw.toml"
hash = "5d179528873996999080475733955a82ddf4e34e675517b9fde1dc2034f101f4"
metafile = true

[[files]]
file = "resourcepacks/cleanview.pw.toml"
hash = "f10eb6f519488b54cc59a155641a8cd0e210b92da9165b04d8f8a8d93d19a22e"
metafile = true

[[files]]
file = "resourcepacks/low-fire-pack.pw.toml"
hash = "3366ba71751957ed753273f5c0fd259c48c1af02f4b239351fd4e7cad4de97aa"
metafile = true

[[files]]
file = "resourcepacks/no-cave-ambience.pw.toml"
hash = "5ecf05c46932dfe09d96b9b7d51ce74da84f59bef3eed65c65282b342a7ef683"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true

[[files]]
file = "shaderpacks/kappa-shader.pw.toml"
hash = "a01d824c592eebca3df5b5af6aed07839eb8b544de20a2e4f276cb0622b203c9"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
